POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNhdWtrbyIsImlkIjoiNjE4MTIyYTI5N2UxODExMjAzY2EzYTEwIiwiaWF0IjoxNjM1ODkyMjk2fQ.Gi-wc5LKmMzB6oNHHUSQFGnFRK9GAqMLLZw4J6MG4oU

{
    "title": "testiblogi2",
    "author": "Tomi Testaaja",
    "url": "http://totallysafeblog.com/testi"
}